version: "3.1"

services:
  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myapp_development
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  app:
    build: .
    volumes: 
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: myapp_development
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
volumes:
  db_data: